### ISSUE TITLE
Floating scroll bars do not work on Safari

### ISSUE THREAD

**Issue by wesley-kiyohara** [Amphiluke/jquery-plugins#7]
Currently on Safari, I am unable to see the horizontal scrollbar until the bottom the div is reached. This is after I've changed my Mac settings to always display scrollbars, and can be seen on each of your demos. Although I cannot see the .fl-scrolls div, I'm still able to hover over where it should be and scroll horizontally.
![scroll](https://cloud.githubusercontent.com/assets/7770422/10062404/29e2c1fe-6217-11e5-8c9a-765ea4799a19.gif)

**Comment by Amphiluke** [comment]
Not sure whether I'll fix this quickly. In fact the plugin was never tested on Mac… So far, the issue stays open  until I have the opportunity to debug it myself on Mac. If you know the way to fix this bug, you're welcome to make a pull request.
Probably pure CSS solutions like [this one](http://stackoverflow.com/a/10100209) will suit you.

**Comment by Amphiluke** [comment]
The issue was fixed in [v2.2.4](https://github.com/Amphiluke/floating-scroll/releases/tag/v2.2.4)
