### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by samjulien** [Amphiluke/jquery-plugins#8]
Can you publish floatingscroll on npm? I'm going to wrap floatingscroll in an Angular directive, would be nice to include this as a dependency instead of manually downloading. If I publish the directive anywhere I will of course credit you and link to this repo.

**Comment by Amphiluke** [comment]
Hello Sam.
I have just published it as [floating-scroll](https://www.npmjs.com/package/floating-scroll) package. Also, the plugin is now in a [separate repo](https://github.com/Amphiluke/floating-scroll) for consistency reasons…
Please let me know if something go wrong with the package (I have never created npm modules before :blush:)

**Comment by samjulien** [comment]
Great, thank you! I will add it to my directive package and let you know if anything goes wrong!

**Comment by Amphiluke** [comment]
Closing the issue. From now on, any floatingScroll-related issues are to be created in the [floating-scroll](https://github.com/Amphiluke/floating-scroll/issues) repo.
